### ISSUE TITLE
Upgrade bugsnag-js to new major version 4

### ISSUE THREAD

**Issue by Alonski** [adopted-ember-addons/ember-cli-bugsnag#81]
Bugsnag has put out a new major version. Currently 4.3.3

This is a complete rewrite that changes how bugsnag is used and thus just upgrading the package doesn't work.
I played around for an hour or so trying to get this to work but couldn't get it working again.

I can help if I get some direction but I don't have a lot of experience with Ember Addons and am running into a few walls.

Here is what I tried so far: https://github.com/Alonski/ember-cli-bugsnag/tree/upgradeBugsnag

**Comment by jasonmevans** [comment]
Looks like the new package is `@bugsnag/js`. Would love an upgrade! 

https://github.com/binhums/ember-cli-bugsnag/blob/3cdda002330d3fb2708289e75a19822e3394a9ad/package.json#L51

Maybe I'll see about a fork. 😄
